### ISSUE TITLE
error while solving on windows

### ISSUE THREAD

**Issue by pazochoa** [joehuchette/BARON.jl#10]
While trying to solve a test model with BARON in a JUliaPro 0.6.2.2 version installed in Windows I ran into this issue.
ERROR: ArgumentError: invalid unicode (\u) escape sequence used in "ResName: \"C:\\Users\\user\\AppData\\Local\\Temp\\res.lst\";"
I think it has to do with the Unicode printing in Windows.

**Comment by joehuchette** [comment]
Others have reported this, and I believe your assessment is correct. Unfortunately I don't have a Windows machine to test or debug, so any PRs with fixes are very welcome.

**Comment by bbrunaud** [comment]
The problem is [this line](https://github.com/joehuchette/BARON.jl/blob/9726059a43aba4ac70ed4f2ca1262ffa5d5f27b4/src/BARON.jl#L200)

Removing the `unescape_string` function solved the issue. Linux and Mac paths are not affected by the function because they use `/` instead of `\` 

Line 200 should be 
```
 println(fp, "$opt: $('"')$setting$('"');")
```

I worked this out with @pazochoa . She sits next to me in the office.

**Comment by joehuchette** [comment]
Thanks! I opened a PR with it in #11. (Feel free to open one in place of it if you would like the commit credit)
