### ISSUE TITLE
Error on setting BARON parameters

### ISSUE THREAD

**Issue by trathi05** [joehuchette/BARON.jl#41]
On trying to specify the maximum time limit parameter using `set_optimizer_attribute` function as follows,
```
set_optimizer(model, BARON.Optimizer)
set_optimizer_attribute(model, "MaxTime", 100)
optimize!(model)
```

Following error is thrown: 
```
ERROR: MathOptInterface.UnsupportedAttribute{MathOptInterface.RawParameter}: Attribute MathOptInterface.RawParameter("MaxTime") is not supported by the model.
```

Same error pops up when I try to set other BARON options mentioned in [BARON manual](http://www.minlp.com/downloads/docs/baron%20manual.pdf). 

Additionally, on trying to retrieve the gap using JuMP function `relative_gap(model)`, the following error pops up: 
```
ERROR: ArgumentError: ModelLike of type BARON.Optimizer does not support accessing the attribute MathOptInterface.RelativeGap()
```

Following are the package versions I am currently using: 

- BARON v0.6.2
- JuMP v0.21.3

Any suggestions on what could be the reason for these errors? Thank you.

**Comment by joehuchette** [comment]
The first should be implemented in #42. It was just a matter of adding some new methods to the MOI interface.

The second is harder, since I don't believe BARON returns a relative gap at completion. If this is the case, then I don't think we want to be computing the value in the wrapper, especially since "relative gap" can mean different things to different people. So you might be stuck computing this on your own, using the primal+dual bounds which are exposed.

**Comment by trathi05** [comment]
That makes sense. Thank you.

**Comment by joehuchette** [comment]
The latest patch release should address the first issue; I'll leave the second as unactionable.
