### ISSUE TITLE
Optimizing over .bar files and/or JuMP.registered functions

### ISSUE THREAD

**Issue by 1ozturkbe** [joehuchette/BARON.jl#47]
Currently, the MWE below: 
``` julia
using JuMP, BARON
m = Model(BARON.Optimizer)
@variable(m, x)
f = x -> x
JuMP.register(m, :f, 1, f, autodiff=true)
@objective(m, Min, x)
@NLconstraint(m, f(x) >= 1)
optimize!(m)
```
Returns an error: ```ERROR: UnrecognizedExpressionException: unrecognized function call expression: f(x[1])```
This problem can be solved with other NL solvers such as Ipopt. 
I know that BARON requires constraints of a certain form, and thus cannot handle arbitrary functions as ```f``` above.  My approach thus far to transcribe nonlinear optimization problems into JuMP.Models (such as .bar files) has been to pose them in a functional form, since JuMP NL programs are picky in syntax, and I didn't want to transcribe large problems by hand. 

My questions are two-fold. (1) Is there a way to transcribe .bar optimization files directly into JuMP.Model? Or alternatively (2) is there a way to use BARON.Optimizer to optimize over JuMP.register'ed functions? Thanks in advance for the help!

**Comment by joehuchette** [comment]
Not sure I understand (1) completely: Do you wish to take a valid .bar file and use it to construct a JuMP.Model? There's currently no way to do this, but it could conceivably be done. You might find some of the internal routines in BARON.jl useful, e.g. https://github.com/joehuchette/BARON.jl/blob/756f2ff5f6b28f35d8553e035c44fdc9f20b12e5/src/util.jl#L258-L302.

(2) Unfortunately not. BARON expects an explicit expression graph, and only supports a small library of functions. A registered function in JuMP is a "black box" in the sense that JuMP does not have access to the expression graph; it instead computes derivatives through forward mode autodifferentiation. In order to use BARON.jl with JuMP, you cannot use registered functions, and there's really no way around that.

**Comment by 1ozturkbe** [comment]
Those were exactly the questions I was asking, thanks @joehuchette. I will likely have to transcribe some other way.
