### ISSUE TITLE
Installing BARON.jl breaks JuMP

### ISSUE THREAD

**Issue by shoshievass** [joehuchette/BARON.jl#9]
I followed the instructions in the readme (installed BARON w/ the license, added the paths, did Pkg.add("BARON")). The last step seems to break JuMP. After the installation, JuMP would not precompile (and would give an error when I tried to run ```using JuMP```. Removing the package resolved the problem, but didn't let me use BARON obviously..

**Comment by rdeits** [comment]
Discourse discussion over at https://discourse.julialang.org/t/jump-does-not-precompile/10141/4

@shoshievass you're seeing issues with JuMP because the latest release of BARON.jl requires a relatively old version of MathProgBase (which JuMP also uses), and that relatively old release does not include the necessary fixes for Julia v0.6. 

@joehuchette I don't see anything obvious in BARON.jl that would prevent it from working on Julia v0.6. Is the upper bound in REQUIRE necessary?

**Comment by joehuchette** [comment]
I've actually made the changes locally but haven't pushed them, I'll do that now :)

**Comment by joehuchette** [comment]
ref https://github.com/JuliaLang/METADATA.jl/pull/14124

**Comment by joehuchette** [comment]
Give it a go now (``Pkg.update()``).

**Comment by shoshievass** [comment]
@joehuchette - this still requires a degrade of MathProgBase, which seems to be causing some issues. Is that a necessary issue?

**Comment by joehuchette** [comment]
From v0.7 to v0.6?

**Comment by shoshievass** [comment]
Yep!
![image](https://user-images.githubusercontent.com/3093378/38699974-9c27d1b2-3e67-11e8-8a45-a3bc08393691.png)

**Comment by shoshievass** [comment]
Yep!


-Shosh

**Comment by joehuchette** [comment]
Tagged a new version with the version bump (https://github.com/JuliaLang/METADATA.jl/pull/14237), pending approval. If you want to try it now, you can do ``Pkg.checkout("BARON")``.

**Comment by shoshievass** [comment]
thanks!

-Shosh

**Comment by shoshievass** [comment]
Getting an error on that (maybe I'm doing something silly?) but I can wait for approval!
![image](https://user-images.githubusercontent.com/3093378/38701472-f28ad64a-3e6b-11e8-8a95-d79c3b337ea7.png)

**Comment by joehuchette** [comment]
If you ran ``Pkg.rm("BARON")``, you need to run ``Pkg.add("BARON")`` afterwards to add it back
